// db/migrations/20250819-demo-event-seeder.js
export default {
    async up(queryInterface, Sequelize) {
        queryInterface.bulkInsert('Events', [
            {
                name: 'Tech Conference 2025',
                subtitle: 'AI & Future',
                date: '2025-09-10',
                time: '10:00:00',
                endDate: '2025-09-10',
                endTime: '18:00:00',
                description: 'A conference about the future of AI and technology innovations.',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Cracow Museum Night',
                subtitle: 'Culture & History',
                date: '2025-09-11',
                time: '10:00:00',
                endDate: '2025-09-10',
                endTime: '18:00:00',
                description: 'Explore the rich history and culture of Cracow with special exhibits and tours.',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Emerging Tech Expo',
                subtitle: 'AI & Future',
                date: '2025-09-11',
                time: '10:00:00',
                endDate: '2025-09-10',
                endTime: '18:00:00',
                description: 'Explore the latest breakthroughs in technology and AI applications.',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Summer Soundwave',
                subtitle: 'Summer Beats',
                date: '2025-09-12',
                time: '15:00:00',
                endDate: '2025-08-22',
                endTime: '23:59:00',
                description: 'Experience three days of live music, sunshine, and unforgettable performances.',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Design Forward',
                subtitle: 'Creative Minds',
                date: '2025-09-13',
                time: '09:00:00',
                endDate: '2025-10-05',
                endTime: '17:00:00',
                description: 'A showcase of cutting-edge art and design from around the world.',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Music Festival',
                subtitle: 'Summer Beats',
                date: '2025-08-20',
                time: '15:00:00',
                endDate: '2025-08-22',
                endTime: '23:59:00',
                description: 'A 3-day music festival with top artists and DJs.',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Art & Design Expo',
                subtitle: 'Creative Minds',
                date: '2025-10-05',
                time: '09:00:00',
                endDate: '2025-10-05',
                endTime: '17:00:00',
                description: 'Exhibition of contemporary art and innovative design.',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Marathon 2025',
                subtitle: 'Run for Charity',
                date: '2025-11-12',
                time: '07:00:00',
                endDate: '2025-11-12',
                endTime: '14:00:00',
                description: 'A city marathon to raise funds for local charities.',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Startup Pitch Night',
                subtitle: 'Innovators Unite',
                date: '2025-09-25',
                time: '18:00:00',
                endDate: '2025-09-25',
                endTime: '21:00:00',
                description: 'Local startups pitch their ideas to investors and mentors.',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Cooking Workshop',
                subtitle: 'Gourmet at Home',
                date: '2025-10-15',
                time: '14:00:00',
                endDate: '2025-10-15',
                endTime: '17:00:00',
                description: 'Hands-on cooking workshop with professional chefs.',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Photography Seminar',
                subtitle: 'Capture the Moment',
                date: '2025-09-18',
                time: '11:00:00',
                endDate: '2025-09-18',
                endTime: '16:00:00',
                description: 'Learn advanced photography techniques from experts.',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Yoga Retreat',
                subtitle: 'Mind & Body',
                date: '2025-12-01',
                time: '08:00:00',
                endDate: '2025-12-03',
                endTime: '18:00:00',
                description: 'A 3-day wellness retreat focusing on yoga, meditation, and healthy living.',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Film Screening',
                subtitle: 'Indie Cinema Night',
                date: '2025-11-05',
                time: '19:00:00',
                endDate: '2025-11-05',
                endTime: '22:00:00',
                description: 'Screening of award-winning independent films with director Q&A.',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Charity Gala',
                subtitle: 'Evening of Giving',
                date: '2025-12-10',
                time: '18:30:00',
                endDate: '2025-12-10',
                endTime: '23:00:00',
                description: 'An elegant evening to raise funds for local nonprofit organizations.',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Science Fair',
                subtitle: 'Innovation in Action',
                date: '2025-10-20',
                time: '10:00:00',
                endDate: '2025-10-20',
                endTime: '16:00:00',
                description: 'Students present science projects and experiments to the public.',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Book Launch',
                subtitle: 'Author Meet & Greet',
                date: '2025-09-30',
                time: '17:00:00',
                endDate: '2025-09-30',
                endTime: '19:00:00',
                description: 'Meet the author and get signed copies of their latest novel.',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Charity Fun Run',
                subtitle: 'Run for Hope',
                date: '2025-11-15',
                time: '09:00:00',
                endDate: '2025-11-15',
                endTime: '12:00:00',
                description: 'A 5K fun run to raise awareness and funds for local charities.',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Tech Hackathon',
                subtitle: 'Code for Good',
                date: '2025-12-05',
                time: '08:00:00',
                endDate: '2025-12-06',
                endTime: '20:00:00',
                description: '48-hour coding marathon for building social impact applications.',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Wine Tasting Event',
                subtitle: 'Vineyard Delights',
                date: '2025-10-25',
                time: '15:00:00',
                endDate: '2025-10-25',
                endTime: '19:00:00',
                description: 'Sample wines from local vineyards and learn about wine pairing.',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Dance Workshop',
                subtitle: 'Move & Groove',
                date: '2025-09-28',
                time: '13:00:00',
                endDate: '2025-09-28',
                endTime: '16:00:00',
                description: 'Interactive dance session covering multiple styles for all skill levels.',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Photography Contest',
                subtitle: 'Capture the City',
                date: '2025-11-01',
                time: '09:00:00',
                endDate: '2025-11-01',
                endTime: '18:00:00',
                description: 'Contest open to all photographers with prizes for top submissions.',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Rock Legends Live',
                subtitle: 'Classic Rock Night',
                date: '2025-09-15',
                time: '20:00:00',
                endDate: '2025-09-15',
                endTime: '23:30:00',
                description: 'A night of timeless rock hits performed by legendary bands.',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Jazz Evening',
                subtitle: 'Smooth & Cool',
                date: '2025-10-10',
                time: '19:00:00',
                endDate: '2025-10-10',
                endTime: '22:00:00',
                description: 'An intimate jazz concert featuring world-class musicians.',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'EDM Night',
                subtitle: 'Electronic Dance Festival',
                date: '2025-08-30',
                time: '21:00:00',
                endDate: '2025-08-31',
                endTime: '03:00:00',
                description: 'High-energy EDM performances with top DJs from around the globe.',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Indie Vibes',
                subtitle: 'Local Indie Artists',
                date: '2025-09-22',
                time: '18:00:00',
                endDate: '2025-09-22',
                endTime: '22:00:00',
                description: 'A showcase of emerging indie bands from the local music scene.',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Symphony in the Park',
                subtitle: 'Orchestral Evening',
                date: '2025-10-18',
                time: '17:00:00',
                endDate: '2025-10-18',
                endTime: '20:00:00',
                description: 'Outdoor symphony performance featuring classical favorites.',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Pop Extravaganza',
                subtitle: 'Top 40 Hits Live',
                date: '2025-11-08',
                time: '19:30:00',
                endDate: '2025-11-08',
                endTime: '23:00:00',
                description: 'Live performances of the biggest pop hits of the year.',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Metal Mayhem',
                subtitle: 'Heavy Metal Night',
                date: '2025-12-05',
                time: '20:00:00',
                endDate: '2025-12-05',
                endTime: '01:00:00',
                description: 'Intense heavy metal concert featuring multiple bands and pyrotechnics.',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Acoustic Lounge',
                subtitle: 'Unplugged Sessions',
                date: '2025-09-27',
                time: '18:00:00',
                endDate: '2025-09-27',
                endTime: '21:00:00',
                description: 'An intimate acoustic concert featuring singer-songwriters.',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Hip Hop Night',
                subtitle: 'Urban Beats',
                date: '2025-10-25',
                time: '20:00:00',
                endDate: '2025-10-25',
                endTime: '23:59:00',
                description: 'Live hip hop performances and freestyle battles by top artists.',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Folk & Roots Festival',
                subtitle: 'Traditional Tunes',
                date: '2025-11-15',
                time: '15:00:00',
                endDate: '2025-11-15',
                endTime: '22:00:00',
                description: 'Celebrating folk and roots music with local and international performers.',
                createdAt: new Date(),
                updatedAt: new Date(),
            },

        ]);
    },

    async down(queryInterface, Sequelize) {
        await queryInterface.bulkDelete('Events', null, {});
    },
};
