
//TODO: mock events, replace with real ones
const featuredEvents = [
    {
        id: "1",
        name: "Koncert Dawida Podsiadło",
        subtitle: "Trasa „POST” – Warszawa",
        date: "2025-09-15",
        time: "20:00",
        description: "Niezapomniany wieczór z jednym z najpopularniejszych polskich artystów. Zagra swoje największe przeboje oraz utwory z nowej płyty.",
    },
    {
        id: "2",
        name: "Noc Muzeów – Muzeum Narodowe",
        subtitle: "Specjalna wystawa impresjonistów",
        description: "Jedna noc, wyjątkowa okazja – zwiedzanie wystawy impresjonistów z Francji i Polski. Oprowadzanie z przewodnikiem i muzyka na żywo.",
        date: "2025-09-15",
        time: "20:00",
    },
    {
        id: "3",
        name: "Festiwal Kina Europejskiego",
        subtitle: "Kino Kultura – 3 dni seansów i spotkań",
        description: "Ponad 20 filmów z całej Europy, spotkania z reżyserami i warsztaty filmowe. Bilety jednodniowe i karnety dostępne online.",
        date: "2025-09-15",
        time: "20:00",
    },
    {
        id: "4",
        name: "Stand-up: Rafał Pacześ",
        subtitle: "Nowy program „Gorzkie Żale”",
        description: "Najbardziej rozpoznawalny stand-uper w Polsce wraca z nowym programem pełnym ciętego humoru i szczerych spostrzeżeń.",
        date: "2025-09-15",
        time: "20:00",
    },
    {
        id: "5",
        name: "Pokaz Mappingu 3D na Zamku Królewskim",
        subtitle: "Światło, historia i dźwięk",
        description: "Multimedialny spektakl łączący światło, muzykę i historię Polski – zapierający dech w piersiach pokaz na fasadzie Zamku Królewskiego.",
        date: "2025-09-15",
        time: "20:00",
    },
];

const events = [
    {
        id: "1",
        name: "Koncert Dawida Podsiadło",
        subtitle: "Trasa „POST” – Warszawa",
        description: "Niezapomniany wieczór z jednym z najpopularniejszych polskich artystów. Zagra swoje największe przeboje oraz utwory z nowej płyty.",
        date: "2025-09-15",
        time: "20:00",
    },
    {
        id: "2",
        name: "Noc Muzeów – Muzeum Narodowe",
        subtitle: "Specjalna wystawa impresjonistów",
        description: "Jedna noc, wyjątkowa okazja – zwiedzanie wystawy impresjonistów z Francji i Polski. Oprowadzanie z przewodnikiem i muzyka na żywo.",
        date: "2025-08-17",
        time: "19:00",
    },
    {
        id: "3",
        name: "Festiwal Kina Europejskiego",
        subtitle: "Kino Kultura – 3 dni seansów i spotkań",
        description: "Ponad 20 filmów z całej Europy, spotkania z reżyserami i warsztaty filmowe. Bilety jednodniowe i karnety dostępne online.",
        date: "2025-7-05",
        time: "17:00",
    },
    {
        id: "4",
        name: "Stand-up: Rafał Pacześ",
        subtitle: "Nowy program „Gorzkie Żale”",
        description: "Najbardziej rozpoznawalny stand-uper w Polsce wraca z nowym programem pełnym ciętego humoru i szczerych spostrzeżeń.",
        date: "2025-07-30",
        time: "20:30",
    },
    {
        id: "5",
        name: "Pokaz Mappingu 3D na Zamku Królewskim",
        subtitle: "Światło, historia i dźwięk",
        description: "Multimedialny spektakl łączący światło, muzykę i historię Polski – zapierający dech w piersiach pokaz na fasadzie Zamku Królewskiego.",
        date: "2025-08-24",
        time: "21:00",
    },
    {
        id: "6",
        name: "Targi Designu – Warsaw Design Days",
        subtitle: "Innowacje, projekty, inspiracje",
        description: "Największe wydarzenie dla miłośników designu w Polsce. Prezentacje projektantów, wykłady, i panele dyskusyjne.",
        date: "2025-09-12",
        time: "10:00",
    },
    {
        id: "7",
        name: "Maraton Komedii Romantycznych",
        subtitle: "Kino Atlantic – noc filmowa",
        description: "Zestaw 5 najlepszych komedii romantycznych ostatnich lat z przerwą na pizzę i quizy z nagrodami.",
        date: "2025-08-22",
        time: "22:00",
    },
    {
        id: "8",
        name: "Konferencja IT Future Minds",
        subtitle: "Nowoczesne technologie i AI",
        description: "Wystąpienia liderów branży technologicznej, panele o przyszłości AI i networkingu startupowego.",
        date: "2025-10-10",
        time: "09:00",
    },
    {
        id: "9",
        name: "Warsztaty Ceramiki Artystycznej",
        subtitle: "Tworzenie własnych dzieł z gliny",
        description: "Zajęcia praktyczne dla dorosłych i młodzieży. Możliwość stworzenia unikalnej ceramiki i wypalenia jej na miejscu.",
        date: "2025-07-07",
        time: "15:00",
    },
    {
        id: "10",
        name: "Silent Disco w Łazienkach Królewskich",
        subtitle: "Trzy kanały, jedna cisza",
        description: "Impreza plenerowa w wyjątkowym otoczeniu parku z muzyką na słuchawkach. Trzy gatunki do wyboru.",
        date: "2025-08-31",
        time: "20:30",
    },
];

export { events, featuredEvents };